### ISSUE TITLE
[EPIC]: Runtime improvements

### ISSUE THREAD

**Issue by wjones127** [lance-format/lance#1111]
This umbrella issue covers improvements to the runtime experience of Lance.
 
* [x] Support cancelling long-running commands
* [x] #2124
* [ ] Support optional progress bars for long-running commands
* [ ] Separate CPU threadpool and IO threadpool
  * See https://thenewstack.io/using-rustlangs-async-tokio-runtime-for-cpu-bound-tasks/
* [ ] Allow disabling use of multi-threading in queries
* [x] #736
* [ ] #1712
* [ ] #1505
* [x] #2119
