### ISSUE TITLE
[EPIC] Polars support

### ISSUE THREAD

**Issue by wjones127** [lance-format/lance#1507]
* [ ] Add a `to_polars()` method that forwards arguments to `to_table()`
* [ ] Validate vector columns become sensible types in Polars
* [ ] Support passing Lance table to Lazy API so that we have native projection and predicate pushdown.
* [ ] Advertise Polars support in documentation and potentially a blog post

**Comment by universalmind303** [comment]
Additionally, polars has a js library https://www.npmjs.com/package/nodejs-polars. It would be cool to add that same level of support to the lance js bindings.

**Comment by wjones127** [comment]
That would be cool indeed. Related issue: https://github.com/lancedb/lancedb/issues/153

**Comment by yliang412** [comment]
Hi @wjones127, I would like to give a try at the tasks mentioned in this issue. Could you assign me to this task?

Several initial questions:

1. Would `to_polars()` include polars as an optional dependency? 
2. Do we want a `DataFrame` or a `LazyFrame` as the return type of `to_polars`?
3. I will do more research on how polars handle projection and predicate pushdown in their lazy API, but does this feature requires anything to be done on the polars side?

Also looking for suggestions to start on the tasks. Thanks a lot!

**Comment by wjones127** [comment]
> Could you assign me to this task?

Sure, done.

> Would to_polars() include polars as an optional dependency?

Yes. We'd like to make sure we don't need to import it until necessary. Related: #1217

> Do we want a DataFrame or a LazyFrame as the return type of to_polars?

Our other APIs are eager right now, so I'd say `DataFrame`. But we could later add a `to_polars_lazy()` that returns a `LazyFrame` if we wanted, but I think getting the pushdown and such correct would take some work that we should defer for later.

> I will do more research on how polars handle projection and predicate pushdown in their lazy API, but does this feature requires anything to be done on the polars side?

We might already be able to work somewhat via pyarrow Dataset API. Part of that implementation is here: https://github.com/pola-rs/polars/blob/64bd3455f0d837f888f2d967cc545e2444f844a8/py-polars/polars/io/pyarrow_dataset/anonymous_scan.py#L14

**Comment by astrojuanlu** [comment]
Is this already done? https://blog.lancedb.com/lancedb-polars-2d5eb32a8aa3/

**Comment by jonasdedden** [comment]
I also worked on a package called `polars-pylance`: https://pypi.org/project/polars-pylance/

It supports both lazy writing and reading from and to polars with Lance in an entirely lazy way, there is extensive support for predicate pushdown optimizations and many other Lance-specific features. It just uses the `polars` and `pylance` Python packages and `polar`'s private `PyLazyFrame.new_from_dataset_object` constructor. I decided against using an IO plugin (reasoning for this [here](https://github.com/jonasdedden/polars-pylance/blob/main/docs/PRIVATE_HOOK_VS_IO_PLUGIN.md)).

I also worked on extensive benchmarks on a large AWS machine with datasets up to 200GiB that show a strong performance and memory load advantage of my package compared to another package called `polars-lance` (which is a compiled extension pinning a specific lance version): https://github.com/jonasdedden/polars-pylance/blob/main/COMPARISON.md
