### ISSUE TITLE
Roadmap 2024

### ISSUE THREAD

**Issue by wjones127** [lance-format/lance#2079]
## Vector search

We continue to work at making vector search performant at very high scales (10 billion vectors).

* [ ] #1832
* [x] #2078
* [ ] #2064

## V2 File Format

We are working on the next version of our Lance file format. The key improvements are null support in all types, columnar compression, and better performance with large blobs.

* [x] #1929
* [x] #1643

## Table format

We want to make table maintenance automatic, if opted into. This would make it much easier to manage tables, since you would not need to manually call operations like compact, re-index, and cleanup.

* [x] #2061
* [ ] Primary keys
  * [x] https://github.com/lancedb/lance/issues/2307
  * [x] https://github.com/lancedb/lance/issues/2454

## Full text search

We will work on native full text search indices for Lance. LanceDB's current implementation of FTS doesn't support incremental updates or working in Node or Rust. Nor does it work on object storage. Implementing FTS at the Lance level will remove these limitations.

* [x] #1195 

## Read / write integration

To make Lance a great choice for AI data lakes, we will be adding connectors to two of the most popular distributed frameworks, Spark and Ray.

* [x] Spark
   * [x] #541
   * [ ] #2062
* [x] #2063

## Query

Finally, there are smaller features we'd like to implement to improve queries. Providing a general SQL front-end for SELECT queries will provide native support for aggregations as well as provide an easy way to implement table views. Bitmap scalar indices will provide much better filter performance on columns with few distinct values.

* [x] Add a `sql` method to execute arbitrary SELECT statements
* [ ] Register user-defined functions for use in projections and filters
* [ ] Table views (dynamic columns)
* [x] Bitmap scalar index #1552
* [ ] More flexible query plans #1782
  * [ ] Filter by `_distance` column #2096

**Comment by westonpace** [comment]
Closing this as 2024 is now over :)
