### ISSUE TITLE
Tracking Lance Datasets (DNC)

### ISSUE THREAD

**Issue by tanaymeh** [lance-format/lance#2086]
This issue tracks the progress of Deep learning datasets created using Lance

- [x] [Text] [Codeparrot GitHub Code dataset variants](https://huggingface.co/datasets/codeparrot/github-code) - [Codeparrot-1M Python](https://www.kaggle.com/datasets/heyytanay/codeparrot-1m)
- [ ] [Text] [Wikitext](https://huggingface.co/datasets/wikitext)
- [ ] [Text] [Common Crawl](https://commoncrawl.org/)
- [ ] [Vision] [Laion 400M](https://laion.ai/blog/laion-400-open-dataset/)
- [ ] [Vision] [Imagenet](https://www.image-net.org/)
- [ ] [Vision] [MS-COCO](https://cocodataset.org/#home)

If you would like to contribute to making these datasets, please reply to this issue with the dataset you wish to make into a Lance dataset and we would be happy to help you!

**Comment by I8dNLo** [comment]
Hi! I would like to help. Could you provide some more detailed guidance of it? Like reference for a good solution for other dataset or so

**Comment by tanaymeh** [comment]
@I8dNLo Thanks for showing an interest in expanding the Lance datasets family!

To know more about how to write a Lance dataset, check out the [Lance Documentation for Reading and Writing Dataset](https://lancedb.github.io/lance/read_and_write.html). Since you showed an interest in Imagenet, here's a doc page that might come in handy for you - [ImageURI](https://lancedb.github.io/lance/arrays.html#imageuri).

I am currently in the process of creating documentation examples for making an Image dataset using Lance but feel free to open a PR if you beat me to it (ha!).

If, however, you want to work with Text datasets, we have a couple of examples of how to do that. Check these out - [Lance Examples](https://lancedb.github.io/lance/examples/examples.html).

Let me know if you need anything else from us!
