### ISSUE TITLE
Epic: Primary keys

### ISSUE THREAD

**Issue by wjones127** [lance-format/lance#2454]
In #2307, we are introducing row ids that are stable after *moves*. If we make them also stable after updates, then the row ids will be usable as primary keys. This will enable operations like get/update/delete by id, making Lance and LanceDB a bit more usable for single row operations.

## Goals
- **Provide a stable primary key for rows.**  These should never change for a row whether it is moved or updated.
- **Primary keys should be guaranteed unique**
- **Rows should be removed from indices if their value was updated, but kept if other parts of the row were updated while the relevant value stayed the same.** For example, if I update a metadata column the vector index should still keep the row I updated. But if I update the vector column, the vector index should no longer keep that row.

## Design

![update stable row id](https://github.com/user-attachments/assets/f2f069be-9b33-497f-93fb-025632c1bfd6)

Shows fragment bitmap changes when applying an update query. The Id column is kept the same, so the new fragment where the row is can still be covered by the id idx. On the other hand, the vector value was changed, so it’s new value should not be part of the vec index.

There are two principal changes:

1. Update queries need to:
    - Re-use for ids for updated rows
    - Keep indexed and unindexed data separate
    - Update index fragment bitmaps appropriately
2. Pre-filter needs to be constructed to only allow row ids that:
    1. Are in fragments that are part of the fragment bitmap
    2. Aren’t deleted in those fragments

## Plan

* [ ] #2802 (8 days remaining)
  * [x] Rename the feature flag from move-stable row ids to primary keys
  * [ ] Update queries with primary keys
     * Preserves row ids, separated indexed and unindexed data, updated frag bitmap
  * [ ] Merge-insert queries with primary keys
     * Preserves row ids, separated indexed and unindexed data, updated frag bitmap
* [ ] **Query path changes** (5 days)
  * [ ] Query path pre-filter handles primary keys
  * [ ] Benchmark query path with primary keys
* [ ] **Compaction changes** (3 days)
  * [ ] Alter compaction planning to prioritize merging fragments to create contiguous row ids
  * [ ] Alter compaction execution to sort by row id

* [ ] **Performance optimizations** (3 days)
  * [ ] Use row id index as the pre-filter in queries
  * [ ] Replace custom bitmap implementation with simpler one
  * [ ] Move large row id sequences to external files.
    * (This requires cleanup also be implemented for those files)

### Follow up work
(not necessary for public release)
* [ ] **Primary key APIs** (3 days)
  * [ ] Can get `_rowid` from user-facing query APIs
  * [ ] Get row by `_rowid`
  * [ ] Update row by `_rowid`
  * [ ] Delete row by `_rowid`

**Comment by jiaoew1991** [comment]
Hi @wjones127 If stable rowid is used, is there an efficient API to retrieve the row address and fragment ID based on the rowid?

**Comment by wjones127** [comment]
Closing this, as we will track future progress in https://github.com/lance-format/lance/issues/8931
