### ISSUE TITLE
Commit loop improvements

### ISSUE THREAD

**Issue by wjones127** [lance-format/lance#2538]
* [x] Start to count each conflict as one conflict instead of `latest - tx_version` number of conflicts
* [ ] Allow transaction level be configured (enable a serializable mode)
* [ ] Allow max conflict retries to be configurable
* [ ] Consider outer retries for operations that need to re-do data operations to retry.
